In [6]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [7]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
x.dtype

dtype('int32')

In [9]:
x.shape

(5,)

In [10]:
Y = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
Y.shape

(4, 3)

In [13]:
Y.size

12

In [23]:
x = np.array(['Hello', 'World'])
print(x)

['Hello' 'World']


In [24]:
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [26]:
x = np.array([1, 2, 'World']) #Numpy arrays must contain elements of only one type
print(x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)

['1' '2' 'World']
shape: (3,)
type: <class 'numpy.ndarray'>
dtype: <U11


**Upcasting: As all elements must be of the same type, numpy selects the most restrictive**

In [27]:
x = np.array([1, 2.5, 4]) 
print(x, x.dtype)

[1.  2.5 4. ] float64


**Specifiying explicitly the type of the numpy array:**

In [36]:
x = np.array([1, 2.5, 7], dtype= np.int64)
print(x)
print('dtype:', x.dtype)

[1 2 7]
dtype: int64


**Saving arrays as files for later reuse:**

In [38]:
x = np.array([1, 2, 4, 5, 6])
np.save('my_array', x)

In [35]:
y = np.load('my_array.npy')
print(y)

[1 2 4 5 6]


**Creating matrix filled with ones or zeroes**

In [43]:
x = np.zeros((3, 4), dtype= int)
print(x)
print(x.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [45]:
x = np.ones((3, 4))
print(x)
print(x.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [47]:
x = np.full((3, 4), 3.14)
print(x)
print(x.dtype)

[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]
float64


**Working with matrix diagonals**

In [50]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
x = np.diag([10, 20, 30, 50])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


**The np.arange function**

In [56]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [59]:
x = np.arange(1, 14, 3)
print(x)

[ 1  4  7 10 13]


**The linspace function**

In [60]:
#Create a 10 evenly spaced list of points from 0 to 25, including start and end points.
x = np.linspace(0, 25, 10) 
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [61]:
#Create a 10 evenly spaced list of points from 0 to 25 not including the endpoint
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


**The reshape function**

In [62]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [63]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [64]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


**Concatenating Numpy functions**

In [68]:
Y = np.arange(20).reshape(2,10)
print(Y)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [67]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


**Working with the random function***

In [76]:
X = np.random.random((3,3))
print(x)

[[0.88142035 0.65001791 0.79430999]
 [0.50324941 0.30499364 0.14327731]
 [0.21164622 0.58801544 0.66977788]]


In [77]:
X = np.random.randint(4, 15,(3,2))
print(X)

[[ 4  4]
 [14 12]
 [ 9 11]]


In [83]:
X = np.random.normal(0, 0.1, size= (1000,1000))
print(X)

[[ 0.20225583  0.06874325  0.02804736 ...  0.09628163 -0.03099073
  -0.06435806]
 [ 0.04120436  0.1253146   0.04219623 ... -0.06364922  0.09706397
   0.06402995]
 [-0.07692276  0.10750924  0.2777837  ...  0.05773654 -0.00223061
   0.02390317]
 ...
 [-0.03611866  0.13414393 -0.07636551 ...  0.16167191 -0.17493731
  -0.07197934]
 [-0.02603448 -0.19511226 -0.10865406 ... -0.03143301 -0.07604886
   0.006139  ]
 [ 0.12369496  0.19881138  0.01653122 ... -0.07013893  0.11952909
   0.03659229]]


In [ ]:
np.linespace(