In [2]:
import numpy as np

X = np.random.randint(0, 10, size= (4, 4))
print(X)

[[4 4 7 0]
 [2 9 7 7]
 [8 2 5 2]
 [5 8 8 5]]


In [5]:
ave_cols = X.mean(axis= 0)
std_cols = X.std(axis= 0)
print(ave_cols)
print(std_cols)

[4.75 5.75 6.75 3.5 ]
[2.16506351 2.86138079 1.08972474 2.6925824 ]


In [9]:
X_norm = (X - ave_cols) / std_cols
print(X_norm)

[[-0.34641016 -0.61159284  0.22941573 -1.29986737]
 [-1.27017059  1.13581527  0.22941573  1.29986737]
 [ 1.5011107  -1.31055608 -1.60591014 -0.55708601]
 [ 0.11547005  0.78633365  1.14707867  0.55708601]]


In [11]:
print(X_norm.mean())
print(X_norm.max(axis= 0))
print(X_norm.min(axis= 0))

5.551115123125783e-17
[1.5011107  1.13581527 1.14707867 1.29986737]
[-1.27017059 -1.31055608 -1.60591014 -1.29986737]
