In [1]:
import numpy as np

**Slicing indexes:**
1. array [start:end]
2. array [start:]
3. array [:end]

In [54]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [55]:
y = X[1:, 2:]
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [56]:
print(X[0,1])
print(X[1,0])

2
6


In [57]:
z = X[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [58]:
z = X[:, 2]
print(z)

[ 3  8 13 18]


**Slicing creates alias to the original array**

Note: To work correctly this cell must be executed the last.

In [59]:
print('X Before:\n', X, '\n')
z[0] = 555
print('X After:\n', X)

X Before:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

X After:
 [[  1   2 555   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


**Creating a copy of an NumPy array**

In [74]:
a = X[:,2].copy()
print(a)

[555   8  13  18]


**Using an array to index another array**

In [61]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [63]:
y = X[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [66]:
z = X[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


**NumPy diagonal function**

In [68]:
print(X)

[[  1   2 555   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [70]:
z = np.diag(X)
print(z)

[ 1  7 13 19]


In [73]:
z = np.diag(X, k= 1) # Selecting elements above the diagonal
print(z)
z = np.diag(X, k= -1) # Selecting elements below the diagonal
print(z)

[ 2  8 14 20]
[ 6 12 18]


**Extracting unique values**

In [78]:
X = np.ones([3,3]) # Creating a matrix with some unique values
X[1,1] = 5
X[2,2] = 7
print(X)

[[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 7.]]


In [80]:
print(np.unique(X))

[1. 5. 7.]
