In [1]:
import numpy as np

In [42]:
x = np.arange(1,6)
print(x)

[1 2 3 4 5]


**Numpy arrays are zero indexed**

In [7]:
print('1st element:', x[0])
print('2nd element:', x[1])
print('5th element:', x[4])

1st element: 1
2nd element: 2
5th element: 5


In [8]:
print('1st element:', x[-5])
print('2nd element:', x[-4])
print('5th element:', x[-1])

1st element: 1
2nd element: 2
5th element: 5


In [9]:
x [3] = 20
print(x)

[ 1  2  3 20  5]


In [10]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print('Element (0,0):', X[0,0])

Element (0,0): 1


In [19]:
x = np.arange(1,6)
print(x)

x = np.delete(x, [0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


**Using the Numpy delete function**

In [38]:
Y = np.arange(1,10).reshape(3,3)
print(Y,'\n')

W = np.delete(Y, 0, axis= 0)
print(W, '\n')

V = np.delete(Y, [0, 2], axis= 1)
print(V, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[2]
 [5]
 [8]] 



**Using the Numpy append function**

In [41]:
x = np.arange(1,8)
print(x)
x = np.append(x, [8, 9])
print(x)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [49]:
X = np.arange(1,10).reshape(3,3)
print(X, '\n')

W = np.append(X, [[10, 11, 12]], axis= 0)
print(W, '\n')

V = np.append(X, [[10],[11],[12]], axis= 1)
print(V, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]] 



**Using the Numpy insert function**

In [51]:
Y = np.array([[1, 2, 3],[7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [54]:
W = np.insert(Y, 1, [4, 5, 6], axis= 0)
print(W)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
V = np.insert(Y, 1, 5, axis= 1)
print(V)

[[1 5 2 3]
 [7 5 8 9]]


**Using the Numpy stack function**

In [56]:
x = np.array([1, 2])
print(x)

[1 2]


In [58]:
y = np.array([[3, 4],[5, 6]])
print(y)

[[3 4]
 [5 6]]


In [59]:
z = np.vstack((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [60]:
w = np.hstack((y, np.reshape(x,(2,1))))
print(w)

[[3 4 1]
 [5 6 2]]
