In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [4]:
print(x + y)
print(np.add(x, y)) # This method has more options available

[ 6  8 10 12]
[ 6  8 10 12]


In [8]:
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [9]:
X = x.reshape(2,2)
print(X)

[[1 2]
 [3 4]]


In [10]:
Y = y.reshape(2,2)
print(Y)

[[5 6]
 [7 8]]


In [12]:
print(X + Y, '\n')
print(X - Y, '\n')
print(X * Y, '\n')
print(X / Y)

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**Applying functions to elements in array**

In [15]:
print(x)
print(np.sqrt(x))
print(np.exp(x))
print(np.power(x, 2))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]


**Some basic statistics**

In [16]:
print(X, '\n')
print('average of all: ', X.mean())

[[1 2]
 [3 4]] 

average of all:  2.5


In [19]:
print('average of columns: ', X.mean(axis= 0))
print('average of rows: ', X.mean(axis= 1))

average of columns:  [2. 3.]
average of rows:  [1.5 3.5]


In [20]:
print(np.median(X))
print(np.std(X))
print(np.max(X))
print(np.min(X))

2.5
1.118033988749895
4
1


**Scalar -> (operation) -> Matrix**

In [21]:
print(X)

[[1 2]
 [3 4]]


In [23]:
print(3 + X)

[[4 5]
 [6 7]]


In [25]:
print(3 * X)

[[ 3  6]
 [ 9 12]]


In [31]:
A = np.arange(9).reshape(3, 3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
b = np.arange(3)
print(b)

[0 1 2]


In [33]:
print(A + b) # Broadcasting to adapt array b to array A

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [40]:
a = np.arange(4)
b = np.ones(4).reshape(4,1)
print(a.shape)
print(b.shape)
print((a + b).shape)
print(a + b)

(4,)
(4, 1)
(4, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
