In [2]:
import numpy as np

**Boolean indexing**

In [3]:
X = np.random.randint(100, size= (5,5))
print(X)

[[61 13 34 28 18]
 [40 47 11 76 96]
 [60 19 94 17 85]
 [64 82 74 87  2]
 [25 87  2 57  6]]


In [4]:
print(X[X < 45])

[13 34 28 18 40 11 19 17  2 25  2  6]


In [5]:
print(X[(X > 10) & (X < 30)])

[13 28 18 11 19 17 25]


**Boolean indexing and assignment operation**

In [6]:
X[(X > 10) & (X < 30)] = 0
print(X)

[[61  0 34  0  0]
 [40 47  0 76 96]
 [60  0 94  0 85]
 [64 82 74 87  2]
 [ 0 87  2 57  6]]


**Set operations**

In [7]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


**Sorting operations**

In [11]:
x = np.random.randint(1, 11, size= 10)
print(x)
print(np.sort(x)) # Sort from min to max

[ 6  3 10  7  5  2  2  9  8  5]
[ 2  2  3  5  5  6  7  8  9 10]


In [12]:
print(np.sort(np.unique(x)))

[ 2  3  5  6  7  8  9 10]


In [13]:
x.sort() # This one affects the original array
print(x)

[ 2  2  3  5  5  6  7  8  9 10]


In [16]:
X = np.random.randint(1, 11, size= (5, 5))
print(X)

[[ 6  2  3  9  9]
 [ 7  3  8  4  2]
 [ 7  5  9  9 10]
 [10  6  8 10  7]
 [ 8  7  6  1  5]]


In [19]:
print(np.sort(X, axis= 0)) # Sort by rows

[[ 6  2  3  1  2]
 [ 7  3  6  4  5]
 [ 7  5  8  9  7]
 [ 8  6  8  9  9]
 [10  7  9 10 10]]


In [18]:
print(np.sort(X, axis= 1)) # Sort by columns

[[ 2  3  6  9  9]
 [ 2  3  4  7  8]
 [ 5  7  9  9 10]
 [ 6  7  8 10 10]
 [ 1  5  6  7  8]]
