In [1]:
import numpy as np

**Boolean indexing**

In [44]:
X = np.random.randint(100, size= (5,5))
print(X)

[[59  6 43 45 79]
 [24 62  0  2 78]
 [35 23 93  0  4]
 [62 40  5 18 14]
 [74 18 60  9 64]]


In [45]:
print(X[X < 45])

[ 6 43 24  0  2 35 23  0  4 40  5 18 14 18  9]


In [46]:
print(X[(X > 10) & (X < 30)])

[24 23 18 14 18]


**Boolean indexing and assignment operation**

In [48]:
X[(X > 10) & (X < 30)] = 0
print(X)

[[59  6 43 45 79]
 [ 0 62  0  2 78]
 [35  0 93  0  4]
 [62 40  5  0  0]
 [74  0 60  9 64]]


**Set operations**

In [52]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]
